# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: NDKline
email: nicholas@theagora.us
description: > # this means to ignore newlines until "baseurl:"
  A programmer at PSU mastering UX, servering content across the globe, and evangelist for a better internet 
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://blog.ndkline.com" # the base hostname & protocol for your site
twitter_username: ndkline
github_username:  ndkline

# Build settings
markdown: kramdown
